const characters = [
  {
    id: 1,
    name: "Baby Daisy",
    weightClass: "light",
    speed: 5,
    weight: 6,
    acceleration: 0,
    handling: 0,
    drift: 0,
    offRoad: 0,
    miniTurbo: 3,
    total: 14,
  },
  {
    id: 2,
    name: "Baby Luigi",
    weightClass: "light",
    speed: 5,
    weight: 8,
    acceleration: 0,
    handling: 0,
    drift: 0,
    offRoad: 0,
    miniTurbo: 0,
    total: 13,
  },
  {
    id: 3,
    name: "Baby Mario",
    weightClass: "light",
    speed: 0,
    weight: 8,
    acceleration: 0,
    handling: 6,
    drift: 0,
    offRoad: 0,
    miniTurbo: 0,
    total: 14,
  },
  {
    id: 4,
    name: "Baby Peach",
    weightClass: "light",
    speed: 3,
    weight: 6,
    acceleration: 3,
    handling: 3,
    drift: 0,
    offRoad: 0,
    miniTurbo: 0,
    total: 15,
  },
  {
    id: 5,
    name: "Dry Bones",
    weightClass: "light",
    speed: 0,
    weight: 0,
    acceleration: 3,
    handling: 0,
    drift: 3,
    offRoad: 0,
    miniTurbo: 6,
    total: 12,
  },
  {
    id: 6,
    name: "Koopa Troopa",
    weightClass: "light",
    speed: 0,
    weight: 0,
    acceleration: 0,
    handling: 3,
    drift: 0,
    offRoad: 0,
    miniTurbo: 6,
    total: 9,
  },
  {
    id: 7,
    name: "Mii (Light)",
    weightClass: "light",
    speed: 3,
    weight: 3,
    acceleration: 0,
    handling: 0,
    drift: 3,
    offRoad: 0,
    miniTurbo: 3,
    total: 12,
  },
  {
    id: 8,
    name: "Toad",
    weightClass: "light",
    speed: 0,
    weight: 0,
    acceleration: 6,
    handling: 0,
    drift: 6,
    offRoad: 0,
    miniTurbo: 0,
    total: 12,
  },
  {
    id: 9,
    name: "Toadette",
    weightClass: "light",
    speed: 3,
    weight: 0,
    acceleration: 0,
    handling: 0,
    drift: 0,
    offRoad: 6,
    miniTurbo: 0,
    total: 9,
  },
  {
    id: 10,
    name: "Birdo",
    weightClass: "medium",
    speed: 0,
    weight: 3,
    acceleration: 0,
    handling: 0,
    drift: 0,
    offRoad: 3,
    miniTurbo: 5,
    total: 11,
  },
  {
    id: 11,
    name: "Bowser Jr.",
    weightClass: "medium",
    speed: 0,
    weight: 0,
    acceleration: 0,
    handling: 0,
    drift: 0,
    offRoad: 3,
    miniTurbo: 3,
    total: 6,
  },
  {
    id: 12,
    name: "Daisy",
    weightClass: "medium",
    speed: 4,
    weight: 0,
    acceleration: 0,
    handling: 2,
    drift: 0,
    offRoad: 0,
    miniTurbo: 3,
    total: 9,
  },
  {
    id: 13,
    name: "Diddy Kong",
    weightClass: "medium",
    speed: 0,
    weight: 0,
    acceleration: 3,
    handling: 0,
    drift: 3,
    offRoad: 0,
    miniTurbo: 5,
    total: 11,
  },
  {
    id: 14,
    name: "Luigi",
    weightClass: "medium",
    speed: 2,
    weight: 6,
    acceleration: 0,
    handling: 0,
    drift: 0,
    offRoad: 0,
    miniTurbo: 0,
    total: 8,
  },
  {
    id: 15,
    name: "Mario",
    weightClass: "medium",
    speed: 0,
    weight: 6,
    acceleration: 2,
    handling: 2,
    drift: 3,
    offRoad: 0,
    miniTurbo: 0,
    total: 13,
  },
  {
    id: 16,
    name: "Mii (Medium)",
    weightClass: "medium",
    speed: 3,
    weight: 3,
    acceleration: 0,
    handling: 0,
    drift: 0,
    offRoad: 3,
    miniTurbo: 3,
    total: 12,
  },
  {
    id: 17,
    name: "Peach",
    weightClass: "medium",
    speed: 2,
    weight: 0,
    acceleration: 5,
    handling: 0,
    drift: 6,
    offRoad: 0,
    miniTurbo: 0,
    total: 13,
  },
  {
    id: 18,
    name: "Yoshi",
    weightClass: "medium",
    speed: 0,
    weight: 3,
    acceleration: 0,
    handling: 0,
    drift: 3,
    offRoad: 5,
    miniTurbo: 0,
    total: 11,
  },
  {
    id: 19,
    name: "Bowser",
    weightClass: "heavy",
    speed: 2,
    weight: 5,
    acceleration: 0,
    handling: 0,
    drift: 3,
    offRoad: 0,
    miniTurbo: 0,
    total: 10,
  },
  {
    id: 20,
    name: "Donkey Kong",
    weightClass: "heavy",
    speed: 0,
    weight: 3,
    acceleration: 2,
    handling: 2,
    drift: 0,
    offRoad: 0,
    miniTurbo: 3,
    total: 10,
  },
  {
    id: 21,
    name: "Dry Bowser",
    weightClass: "heavy",
    speed: 0,
    weight: 0,
    acceleration: 0,
    handling: 0,
    drift: 0,
    offRoad: 6,
    miniTurbo: 6,
    total: 12,
  },
  {
    id: 22,
    name: "Funky Kong",
    weightClass: "heavy",
    speed: 4,
    weight: 0,
    acceleration: 0,
    handling: 0,
    drift: 0,
    offRoad: 3,
    miniTurbo: 0,
    total: 7,
  },
  {
    id: 23,
    name: "King Boo",
    weightClass: "heavy",
    speed: 0,
    weight: 0,
    acceleration: 0,
    handling: 5,
    drift: 0,
    offRoad: 3,
    miniTurbo: 0,
    total: 8,
  },
  {
    id: 24,
    name: "Mii (Heavy)",
    weightClass: "heavy",
    speed: 3,
    weight: 0,
    acceleration: 3,
    handling: 3,
    drift: 3,
    offRoad: 0,
    miniTurbo: 0,
    total: 12,
  },
  {
    id: 25,
    name: "Rosalina",
    weightClass: "heavy",
    speed: 3,
    weight: 0,
    acceleration: 0,
    handling: 3,
    drift: 0,
    offRoad: 0,
    miniTurbo: 3,
    total: 9,
  },
  {
    id: 26,
    name: "Waluigi",
    weightClass: "heavy",
    speed: 0,
    weight: 0,
    acceleration: 6,
    handling: 0,
    drift: 5,
    offRoad: 3,
    miniTurbo: 0,
    total: 14,
  },
  {
    id: 27,
    name: "Wario",
    weightClass: "heavy",
    speed: 0,
    weight: 3,
    acceleration: 0,
    handling: 0,
    drift: 0,
    offRoad: 3,
    miniTurbo: 6,
    total: 12,
  },
];

module.exports = { characters };
